version: "3.9"
services:
  maxima:
    image: mathinstitut/goemaxima:2022082900-latest
    tmpfs:
      - "/tmp"
    restart: unless-stopped
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - KILL
    cap_drop:
      - ALL
    read_only: true
  stack:
    build:
      context: .
#Uncomment the next lines for a development setup
#      args:
#        ENVIRONMENT: development
#    volumes:
#      - ./:/srv/stack
    restart: unless-stopped
    ports:
      - 3080:80
