site_name: STACK Documentation
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
theme:
    name: bootstrap
    custom_dir: overrides
    logo: img/logo_large.svg
docs_dir: 'doc/en'
markdown_extensions:
    - mdx_math