site_name: STACK Documentation

#Set the path of the docs
docs_dir: doc/en/

#Set the theme of the page
theme: slate

#Support MathJax
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math

