version: "3.9"
services:
  maxima:
    image: mathinstitut/goemaxima:2023010400-latest
    tmpfs:
      - "/tmp"
    restart: unless-stopped
    cap_add:
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    read_only: true
  php:
    build:
      context: ./../../
      dockerfile: ./api/docker/php/Dockerfile
      target: development
#       target: profiling
    volumes:
      - plots:/var/data/api/stack/plots
      - ../../:/srv/stack
      - ../profiles:/profiles
    restart: unless-stopped
  web:
    build:
      context: ./nginx
    volumes:
      - plots:/var/www/plots
    ports:
      - '3080:80'

volumes:
  plots:
